# -*- coding: utf-8 -*-
"""Lab-3-Dl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iSS6Akhk6PLQFvvQ9Y4_77AL-1cadIC
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras import Model, Input

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

class_names = [
    "airplane", "automobile", "bird", "cat", "deer",
    "dog", "frog", "horse", "ship", "truck"
]

print("Training images:", x_train.shape)
print("Training labels:", y_train.shape)
print("Test images:", x_test.shape)
print("Test labels:", y_test.shape)

plt.figure(figsize=(10, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis("off")

plt.tight_layout()
plt.show()

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

y_train = y_train.squeeze()
y_test = y_test.squeeze()

print(y_train[:10])
print([class_names[label] for label in y_train[:10]])

class_counts = np.bincount(y_train)

plt.figure(figsize=(10, 4))
plt.bar(class_names, class_counts)
plt.title("CIFAR-10 Training Class Distribution")
plt.ylabel("Number of images")
plt.xticks(rotation=45)
plt.show()

print(class_counts)

from tensorflow.keras import models, layers

model = models.Sequential([
    layers.Input(shape=(32, 32, 3)),

    # Feature extraction block 1
    layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
    layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),

    # Feature extraction block 2
    layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),

    # Feature extraction block 3
    layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),

    # Classification head
    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dense(10, activation="softmax")
])

model.summary()

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=15,
    batch_size=64,
    verbose=1
)

plt.figure(figsize=(12, 4))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"], label="Training accuracy")
plt.plot(history.history["val_accuracy"], label="Validation accuracy")
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history["loss"], label="Training loss")
plt.plot(history.history["val_loss"], label="Validation loss")
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)

print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_accuracy:.4f}")

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Predicted probabilities → predicted class IDs
y_prob = model.predict(x_test)
y_pred = np.argmax(y_prob, axis=1)

# Precision, recall, and F1-score for every class
print(classification_report(
    y_test,
    y_pred,
    target_names=class_names
))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
plt.imshow(cm, cmap="Blues")
plt.title("Confusion Matrix")
plt.colorbar()

plt.xticks(range(10), class_names, rotation=45)
plt.yticks(range(10), class_names)

plt.xlabel("Predicted label")
plt.ylabel("True label")

for i in range(10):
    for j in range(10):
        plt.text(j, i, cm[i, j],
                 ha="center", va="center",
                 color="white" if cm[i, j] > cm.max() / 2 else "black")

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 10))

for i in range(25):
    plt.subplot(5, 5, i + 1)

    image_index = np.random.randint(len(x_test))
    plt.imshow(x_test[image_index])

    true_label = class_names[y_test[image_index]]
    predicted_label = class_names[y_pred[image_index]]

    color = "green" if true_label == predicted_label else "red"

    plt.title(
        f"True: {true_label}\nPred: {predicted_label}",
        color=color,
        fontsize=8
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# Just running one prediction forces Keras to build the input/output graph
_ = model.predict(x_train[:1])

# Now try again
conv_layer_outputs = [layer.output for layer in model.layers if isinstance(layer, tf.keras.layers.Conv2D)]
conv_layer_names = [layer.name for layer in model.layers if isinstance(layer, tf.keras.layers.Conv2D)]

feature_map_model = tf.keras.models.Model(inputs=model.input, outputs=conv_layer_outputs)

inputs = Input(shape=(32, 32, 3))

# Pass it through each layer of your trained model, in order
x = inputs
conv_outputs = []
conv_names = []

for layer in model.layers:
    x = layer(x)
    if isinstance(layer, tf.keras.layers.Conv2D):
        conv_outputs.append(x)
        conv_names.append(layer.name)

# Build the feature-map extraction model
feature_map_model = Model(inputs=inputs, outputs=conv_outputs)

print("Conv layers being visualized:", conv_names)
feature_map_model.summary()

img_index = 7
sample_img = x_test[img_index]
sample_img_batch = np.expand_dims(sample_img, axis=0)

plt.imshow(sample_img)
plt.title(f"Input image (label: {class_names[y_test[img_index]]})")
plt.axis('off')
plt.show()

feature_maps = feature_map_model.predict(sample_img_batch)

for layer_name, fmap in zip(conv_names, feature_maps):
    num_filters = fmap.shape[-1]
    size = fmap.shape[1]  # spatial size of feature map (e.g., 32, 16, 8)

    # Show only up to 16 filters per layer so plots stay readable
    n_show = min(num_filters, 16)
    cols = 8
    rows = int(np.ceil(n_show / cols))

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 1.5, rows * 1.5))
    fig.suptitle(f"Feature maps — {layer_name} (shape: {fmap.shape[1:]})", fontsize=12)

    for i, ax in enumerate(axes.flat):
        if i < n_show:
            ax.imshow(fmap[0, :, :, i], cmap='viridis')
            ax.set_title(f'f{i}', fontsize=8)
        ax.axis('off')

    plt.tight_layout()
    plt.show()

fig, axes = plt.subplots(1, 2, figsize=(8, 4))

axes[0].imshow(feature_maps[0][0, :, :, 5], cmap='viridis')
axes[0].set_title(f"Early layer: {conv_names[0]}, filter 5")
axes[0].axis('off')

axes[1].imshow(feature_maps[-1][0, :, :, 5], cmap='viridis')
axes[1].set_title(f"Deep layer: {conv_names[-1]}, filter 5")
axes[1].axis('off')

plt.tight_layout()
plt.show()

# For the MaxPooling model
inputs = layers.Input(shape=(32, 32, 3))
x = inputs
max_pool_outputs = []
for layer in model.layers:
    x = layer(x)
    if isinstance(layer, (layers.MaxPooling2D, layers.AveragePooling2D)):
        max_pool_outputs.append(x)

max_pool_feature_model = models.Model(inputs=inputs, outputs=max_pool_outputs)
max_pool_feature_maps = max_pool_feature_model.predict(sample_img_batch)


# --- FIX STARTS HERE ---
# The NameError occurs because `avg_pool_model` is not defined when first used.
# We need to construct a new functional model that is identical to `model`
# but replaces MaxPooling2D layers with AveragePooling2D layers.
# This new model will reuse the weights of the existing Conv2D and Dense layers.

avg_pool_inputs = layers.Input(shape=(32, 32, 3))
x_avg_pool = avg_pool_inputs
avg_pool_feature_outputs = []

for layer in model.layers:
    if isinstance(layer, layers.MaxPooling2D):
        # Create an AveragePooling2D layer with the same configuration as the original MaxPooling2D
        pooling_layer = layers.AveragePooling2D(
            pool_size=layer.pool_size,
            strides=layer.strides,
            padding=layer.padding,
            name=f"avg_{layer.name}" # Give it a unique name
        )
        x_avg_pool = pooling_layer(x_avg_pool)
    elif isinstance(layer, layers.InputLayer):
        # Skip the InputLayer from the original model; our new model already has `avg_pool_inputs`
        continue
    else:
        # For other layers (Conv2D, Dense, Flatten), apply the original layer instance.
        # This reuses the trained weights of these layers.
        x_avg_pool = layer(x_avg_pool)

    # Collect outputs from pooling layers (now AveragePooling2D or original AveragePooling2D if any)
    if isinstance(layer, (layers.MaxPooling2D, layers.AveragePooling2D)):
        avg_pool_feature_outputs.append(x_avg_pool)

# Build the feature extraction model for average pooling
avg_pool_feature_model = models.Model(inputs=avg_pool_inputs, outputs=avg_pool_feature_outputs)
avg_pool_feature_maps = avg_pool_feature_model.predict(sample_img_batch)
# --- FIX ENDS HERE ---


# Now compare the FIRST pooling layer's output (16x16, since input was 32x32)
fig, axes = plt.subplots(1, 2, figsize=(8, 4))
axes[0].imshow(max_pool_feature_maps[0][0, :, :, 5], cmap='viridis')
axes[0].set_title(f"After MaxPooling — shape {max_pool_feature_maps[0].shape[1:3]}")
axes[0].axis('off')

axes[1].imshow(avg_pool_feature_maps[0][0, :, :, 5], cmap='viridis')
axes[1].set_title(f"After AveragePooling — shape {avg_pool_feature_maps[0].shape[1:3]}")
axes[1].axis('off')

plt.tight_layout()
plt.show()

print("MaxPooling values (5x5 patch):")
print(max_pool_feature_maps[0][0, :5, :5, 5])
print("\nAveragePooling values (5x5 patch):")
print(avg_pool_feature_maps[0][0, :5, :5, 5])

max_vals = max_pool_feature_maps[0][0, :, :, 5]
avg_vals = avg_pool_feature_maps[0][0, :, :, 5]

print(f"MaxPooling  -> mean: {max_vals.mean():.4f}, max: {max_vals.max():.4f}, std: {max_vals.std():.4f}")
print(f"AvgPooling  -> mean: {avg_vals.mean():.4f}, max: {avg_vals.max():.4f}, std: {avg_vals.std():.4f}")

from tensorflow.keras import layers

print(f"{'Layer':<12}{'Params':<12}{'Kernel':<12}{'Filters'}")
print("-" * 50)

total_conv_params = 0
for layer in model.layers:
    if isinstance(layer, layers.Conv2D):
        params = layer.count_params()
        total_conv_params += params
        print(f"{layer.name:<12}{params:<12}{str(layer.kernel_size):<12}{layer.filters}")

print("-" * 50)
print(f"Total params in Conv2D layers : {total_conv_params}")
print(f"Total params in full model    : {model.count_params()}")
print(f"Conv layers % of total params : {total_conv_params / model.count_params() * 100:.2f}%")

print("Manual verification:")
print(f"Conv1 (3x3, in=3,  filters=32):  (3*3*3 + 1) * 32   = {(3*3*3+1)*32}")
print(f"Conv2 (3x3, in=32, filters=32):  (3*3*32 + 1) * 32  = {(3*3*32+1)*32}")
print(f"Conv3 (3x3, in=32, filters=64):  (3*3*32 + 1) * 64  = {(3*3*32+1)*64}")
print(f"Conv4 (3x3, in=64, filters=128): (3*3*64 + 1) * 128 = {(3*3*64+1)*128}")

first_conv_layer = model.layers[0]  # conv2d
filters, biases = first_conv_layer.get_weights()

# Normalize filter values to 0-1 for visualization
f_min, f_max = filters.min(), filters.max()
filters_normalized = (filters - f_min) / (f_max - f_min)

plt.figure(figsize=(9, 9))
n_filters_to_show = 9
for i in range(n_filters_to_show):
    plt.subplot(3, 3, i + 1)
    plt.imshow(filters_normalized[:, :, :, i])
    plt.title(f"Filter {i+1}")
    plt.axis("off")

plt.suptitle("First Convolutional Layer Filters")
plt.tight_layout()
plt.show()

def plot_feature_maps(fmap, layer_title, n_show=16, cols=4):
    rows = int(np.ceil(n_show / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 2, rows * 2))
    fig.suptitle(f"Feature Maps - {layer_title}")
    for i, ax in enumerate(axes.flat):
        if i < n_show and i < fmap.shape[-1]:
            ax.imshow(fmap[0, :, :, i], cmap="gray")
        ax.axis("off")
    plt.tight_layout()
    plt.show()

# Fig 7: Layer 1
plot_feature_maps(feature_maps[0], conv_names[0])

# Fig 8: Layer 2
plot_feature_maps(feature_maps[1], conv_names[1])

from sklearn.metrics import precision_recall_fscore_support, accuracy_score

test_acc = accuracy_score(y_test, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average="weighted")

print(f"Test Accuracy       : {test_acc:.4f}")
print(f"Precision (weighted) : {precision:.4f}")
print(f"Recall (weighted)    : {recall:.4f}")
print(f"F1-score (weighted)  : {f1:.4f}")

def build_variant_model(kernel_size=(3,3), stride=(1,1), padding="same",
                         filters=(32,64), pooling_type="max"):
    PoolingLayer = layers.MaxPooling2D if pooling_type == "max" else layers.AveragePooling2D
    m = models.Sequential([
        layers.Input(shape=(32, 32, 3)),
        layers.Conv2D(filters[0], kernel_size, strides=stride, activation="relu", padding=padding),
        PoolingLayer((2, 2)),
        layers.Conv2D(filters[1], kernel_size, strides=stride, activation="relu", padding=padding),
        PoolingLayer((2, 2)),
        layers.Flatten(),
        layers.Dense(128, activation="relu"),
        layers.Dense(10, activation="softmax")
    ])
    return m

def train_and_eval(m, optimizer="adam", batch_size=64, epochs=5):
    m.compile(optimizer=optimizer, loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    m.fit(x_train, y_train, validation_split=0.1, epochs=epochs, batch_size=batch_size, verbose=0)
    _, acc = m.evaluate(x_test, y_test, verbose=0)
    return acc

results = {}

# ---- Pooling type ----
for pooling in ["max", "avg"]:
    m = build_variant_model(pooling_type=pooling)
    acc = train_and_eval(m)
    results[("pooling", pooling)] = acc
    print(f"Pooling={pooling}: acc={acc:.4f}")

# ---- Kernel size ----
for k in [(3,3), (5,5)]:
    m = build_variant_model(kernel_size=k)
    acc = train_and_eval(m)
    results[("kernel", k)] = acc
    print(f"Kernel={k}: acc={acc:.4f}")

# ---- Stride ----
for s in [(1,1), (2,2)]:
    m = build_variant_model(stride=s)
    acc = train_and_eval(m)
    results[("stride", s)] = acc
    print(f"Stride={s}: acc={acc:.4f}")

# ---- Padding ----
for p in ["same", "valid"]:
    m = build_variant_model(padding=p)
    acc = train_and_eval(m)
    results[("padding", p)] = acc
    print(f"Padding={p}: acc={acc:.4f}")

# ---- Number of filters ----
for f in [(16,32), (32,64), (64,128)]:
    m = build_variant_model(filters=f)
    acc = train_and_eval(m)
    results[("filters", f)] = acc
    print(f"Filters={f}: acc={acc:.4f}")

# ---- Optimizer ----
for opt in ["adam", "sgd", "rmsprop"]:
    m = build_variant_model()
    acc = train_and_eval(m, optimizer=opt)
    results[("optimizer", opt)] = acc
    print(f"Optimizer={opt}: acc={acc:.4f}")

# ---- Batch size ----
for bs in [32, 64, 128]:
    m = build_variant_model()
    acc = train_and_eval(m, batch_size=bs)
    results[("batch_size", bs)] = acc
    print(f"Batch size={bs}: acc={acc:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

pooling_labels = ["max", "avg"]
pooling_vals = [results[("pooling", p)] for p in pooling_labels]
axes[0].bar(pooling_labels, pooling_vals, color=["#4C72B0", "#C44E52"])
axes[0].set_ylim(0, 1.0)
axes[0].set_title("Effect of Pooling Strategy on Test Accuracy")
axes[0].set_xlabel("Pooling Type")
axes[0].set_ylabel("Test Accuracy")

kernel_labels = ["(3, 3)", "(5, 5)"]
kernel_vals = [results[("kernel", (3,3))], results[("kernel", (5,5))]]
axes[1].bar(kernel_labels, kernel_vals, color=["#4C72B0", "#C44E52"])
axes[1].set_ylim(0, 1.0)
axes[1].set_title("Effect of Kernel Size on Test Accuracy")
axes[1].set_xlabel("Kernel Size")
axes[1].set_ylabel("Test Accuracy")

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

stride_labels = ["(1, 1)", "(2, 2)"]
stride_vals = [results[("stride", (1,1))], results[("stride", (2,2))]]
axes[0].bar(stride_labels, stride_vals, color=["#4C72B0", "#C44E52"])
axes[0].set_ylim(0, 1.0)
axes[0].set_title("Effect of Stride on Test Accuracy")
axes[0].set_xlabel("Stride")
axes[0].set_ylabel("Test Accuracy")

padding_labels = ["same", "valid"]
padding_vals = [results[("padding", p)] for p in padding_labels]
axes[1].bar(padding_labels, padding_vals, color=["#4C72B0", "#C44E52"])
axes[1].set_ylim(0, 1.0)
axes[1].set_title("Effect of Padding on Test Accuracy")
axes[1].set_xlabel("Padding")
axes[1].set_ylabel("Test Accuracy")

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

filter_labels = ["(16, 32)", "(32, 64)", "(64, 128)"]
filter_vals = [results[("filters", (16,32))], results[("filters", (32,64))], results[("filters", (64,128))]]
axes[0].bar(filter_labels, filter_vals, color=["#4C72B0", "#C44E52", "#55A868"])
axes[0].set_ylim(0, 1.0)
axes[0].set_title("Effect of Number of Filters on Test Accuracy")
axes[0].set_xlabel("Filters (Conv1, Conv2)")
axes[0].set_ylabel("Test Accuracy")

opt_labels = ["adam", "sgd", "rmsprop"]
opt_vals = [results[("optimizer", o)] for o in opt_labels]
axes[1].bar(opt_labels, opt_vals, color=["#4C72B0", "#C44E52", "#55A868"])
axes[1].set_ylim(0, 1.0)
axes[1].set_title("Effect of Optimizer on Test Accuracy")
axes[1].set_xlabel("Optimizer")
axes[1].set_ylabel("Test Accuracy")

plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
bs_labels = ["32", "64", "128"]
bs_vals = [results[("batch_size", 32)], results[("batch_size", 64)], results[("batch_size", 128)]]
plt.bar(bs_labels, bs_vals, color=["#4C72B0", "#C44E52", "#55A868"])
plt.ylim(0, 1.0)
plt.title("Effect of Batch Size on Test Accuracy")
plt.xlabel("Batch Size")
plt.ylabel("Test Accuracy")
plt.show()

import pandas as pd

summary_rows = [
    ("Pooling", "max", results[("pooling","max")]),
    ("Pooling", "avg", results[("pooling","avg")]),
    ("Kernel Size", "(3, 3)", results[("kernel",(3,3))]),
    ("Kernel Size", "(5, 5)", results[("kernel",(5,5))]),
    ("Stride", "(1, 1)", results[("stride",(1,1))]),
    ("Stride", "(2, 2)", results[("stride",(2,2))]),
    ("Padding", "same", results[("padding","same")]),
    ("Padding", "valid", results[("padding","valid")]),
    ("Filters", "(16, 32)", results[("filters",(16,32))]),
    ("Filters", "(32, 64)", results[("filters",(32,64))]),
    ("Filters", "(64, 128)", results[("filters",(64,128))]),
    ("Optimizer", "adam", results[("optimizer","adam")]),
    ("Optimizer", "sgd", results[("optimizer","sgd")]),
    ("Optimizer", "rmsprop", results[("optimizer","rmsprop")]),
    ("Batch Size", 32, results[("batch_size",32)]),
    ("Batch Size", 64, results[("batch_size",64)]),
    ("Batch Size", 128, results[("batch_size",128)]),
]

summary_df = pd.DataFrame(summary_rows, columns=["Hyperparameter", "Value", "Test Accuracy"])
summary_df

print(f"Pooling max: {results[('pooling','max')]:.4f}")
print(f"Pooling avg: {results[('pooling','avg')]:.4f}")
print(f"Kernel (3,3): {results[('kernel',(3,3))]:.4f}")
print(f"Kernel (5,5): {results[('kernel',(5,5))]:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

pooling_labels = ["max", "avg"]
pooling_vals = [results[("pooling", p)] for p in pooling_labels]
axes[0].bar(pooling_labels, pooling_vals, color=["#4C72B0", "#C44E52"])
axes[0].set_ylim(min(pooling_vals) - 0.05, max(pooling_vals) + 0.05)  # zoomed range
axes[0].set_title("Effect of Pooling Strategy on Test Accuracy")

kernel_labels = ["(3, 3)", "(5, 5)"]
kernel_vals = [results[("kernel", (3,3))], results[("kernel", (5,5))]]
axes[1].bar(kernel_labels, kernel_vals, color=["#4C72B0", "#C44E52"])
axes[1].set_ylim(min(kernel_vals) - 0.05, max(kernel_vals) + 0.05)
axes[1].set_title("Effect of Kernel Size on Test Accuracy")

plt.tight_layout()
plt.show()

