# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhfV5TjmyOMPwOufCtPKhaNVOL9dWGaC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.datasets import fashion_mnist
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
from sklearn.metrics import classification_report
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV

!pip install scikeras

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
print(x_train.shape)
print(y_train.shape)

print(x_train[0:10])

class_names = [
    'T-shirt/Top', 'Trouser', 'Pullover', 'Dress',
    'Coat', 'Sandal', 'Shirt', 'Sneaker',
    'Bag', 'Ankle Boot'
]

plt.figure(figsize=(15, 3))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i], cmap='gray')
    plt.title(class_names[y_train[i]])
    plt.axis('off')
counts = np.bincount(y_train)

plt.figure(figsize=(10,5))
plt.bar(class_names, counts)
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.title("Class Distribution of Fashion-MNIST Training Dataset")
plt.xticks(rotation=45)
plt.savefig("validation_accuracy.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()
plt.tight_layout()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

print(x_train.shape)
print(x_test.shape)

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

print(x_train.dtype)

print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

encoder = OneHotEncoder(sparse_output=False)
y_train = encoder.fit_transform(y_train.reshape(-1, 1))
y_test = encoder.transform(y_test.reshape(-1, 1))

model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(x_test, y_test)
)

plt.figure(figsize=(6,4))
plt.plot(history.history['accuracy'], linewidth=2)
plt.title('Training Accuracy vs Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)

plt.savefig("baseline_training_accuracy.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history['val_accuracy'], linewidth=2)
plt.title('Validation Accuracy vs Epoch')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.grid(True)

plt.savefig("baseline_validation_accuracy.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history['loss'], linewidth=2)
plt.title('Training Loss vs Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)

plt.savefig("baseline_training_loss.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history['val_loss'], linewidth=2)
plt.title('Validation Loss vs Epoch')
plt.xlabel('Epoch')
plt.ylabel('Validation Loss')
plt.grid(True)

plt.savefig("baseline_validation_loss.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

y_pred = model.predict(x_test)

# Convert probabilities to class labels
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_true, y_pred_classes)
precision = precision_score(y_true, y_pred_classes, average='weighted')
recall = recall_score(y_true, y_pred_classes, average='weighted')
f1 = f1_score(y_true, y_pred_classes, average='weighted')

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

cm = confusion_matrix(y_true, y_pred_classes)

print("Confusion Matrix:")
print(cm)

from sklearn.metrics import classification_report

class_names = [
    'T-shirt/Top', 'Trouser', 'Pullover', 'Dress',
    'Coat', 'Sandal', 'Shirt', 'Sneaker',
    'Bag', 'Ankle Boot'
]

print(classification_report(
    y_true,
    y_pred_classes,
    target_names=class_names
))

def create_model(hidden_layers=1,
                 hidden_neurons=128,
                 learning_rate=0.001,
                 optimizer="adam",
                 activation="relu",
                 dropout_rate=0.0):

    model = Sequential()

    # First hidden layer
    model.add(Dense(hidden_neurons,
                    activation=activation,
                    input_shape=(784,)))

    if dropout_rate > 0:
        model.add(Dropout(dropout_rate))

    # Additional hidden layers
    for _ in range(hidden_layers - 1):
        model.add(Dense(hidden_neurons,
                        activation=activation))

        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))

    # Output layer
    model.add(Dense(10, activation="softmax"))

    # Optimizer
    if optimizer == "adam":
        opt = Adam(learning_rate=learning_rate)
    elif optimizer == "sgd":
        opt = SGD(learning_rate=learning_rate)
    else:
        opt = RMSprop(learning_rate=learning_rate)

    model.compile(
        optimizer=opt,
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

clf = KerasClassifier(
    model=create_model,
    verbose=0
)

param_dist = {

    "model__hidden_layers":[1,2,3],

    "model__hidden_neurons":[32,64,128,256],

    "model__learning_rate":[0.1,0.01,0.001],

    "model__optimizer":["adam","sgd","rmsprop"],

    "model__activation":["relu","tanh","sigmoid"],

    "model__dropout_rate":[0.0,0.2,0.5],

    "batch_size":[16,32,64,128],

    "epochs":[10,20,30]
}

random_search = RandomizedSearchCV(
    estimator=clf,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=42,
    verbose=2,
    n_jobs=1
)

random_search.fit(x_train, y_train)

!pip install scikeras==0.13.0 scikit-learn==1.6.1

import sklearn
import tensorflow as tf
import scikeras

print("scikit-learn:", sklearn.__version__)
print("TensorFlow:", tf.__version__)
print("SciKeras:", scikeras.__version__)

from scikeras.wrappers import KerasClassifier

clf = KerasClassifier(model=create_model)

print(clf)

!pip install -q scikit-learn==1.5.2

import sklearn
print(sklearn.__version__)

!pip uninstall -y scikit-learn
!pip install scikit-learn==1.5.2

print(random_search.best_params_)
print(random_search.best_score_)

y_pred = random_search.predict(x_test)

y_true = np.argmax(y_test, axis=1)
y_pred_labels = np.argmax(y_pred, axis=1)

print("Accuracy :", accuracy_score(y_true, y_pred_labels))
print("Precision:", precision_score(y_true, y_pred_labels, average="weighted"))
print("Recall   :", recall_score(y_true, y_pred_labels, average="weighted"))
print("F1-score :", f1_score(y_true, y_pred_labels, average="weighted"))

print("\nClassification Report")
print(classification_report(y_true, y_pred_labels))

cm = confusion_matrix(y_true, y_pred_labels)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Optimized Model")
plt.show()

print(y_test.shape)
print(y_pred.shape)

print(type(y_test))
print(type(y_pred))

best_params = random_search.best_params_

best_model = create_model(
    hidden_layers=best_params["model__hidden_layers"],
    hidden_neurons=best_params["model__hidden_neurons"],
    learning_rate=best_params["model__learning_rate"],
    optimizer=best_params["model__optimizer"],
    activation=best_params["model__activation"],
    dropout_rate=best_params["model__dropout_rate"]
)

history = best_model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=best_params["epochs"],
    batch_size=best_params["batch_size"],
    verbose=1
)

plt.figure(figsize=(6,4))
plt.plot(history.history["accuracy"])
plt.title("Training Accuracy vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid(True)

plt.savefig("training_accuracy.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history["val_accuracy"])
plt.title("Validation Accuracy vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.grid(True)

plt.savefig("validation_accuracy.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history["loss"])
plt.title("Training Loss vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)

plt.savefig("training_loss.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history["val_loss"])
plt.title("Validation Loss vs Epoch")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.grid(True)

plt.savefig("validation_loss.eps", format="eps", dpi=600, bbox_inches="tight")
plt.show()

