# -*- coding: utf-8 -*-
"""lab_5_dl_block_by_block.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MhmuUNzhDKWTiREecqowOEcOVEAMF5E

# CS3807 Deep Learning Laboratory — Experiment 5

Continuation of the submitted `lab_5_dl.py`, organized block-by-block so each experiment can be reviewed and run separately.

**Important:** the assignment requires the independent test set to remain untouched during hyperparameter selection. The cross-validation section therefore uses only the original training + validation data.
"""

# ============================================================
# BLOCK 1 — Imports and Dataset Download
# ============================================================

import pandas as pd
import numpy as np
import os
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

import kagglehub

# Download latest version
path = kagglehub.dataset_download("tanlikesmath/the-oxfordiiit-pet-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))

# ============================================================
# BLOCK 2 — Inspect Dataset and Extract Breed Labels
# ============================================================

from pathlib import Path
import re
import numpy as np

dataset_path = Path(path)

for p in dataset_path.rglob("*.jpg"):
    print(p)
    break

image_dir = dataset_path / "images"

image_paths = sorted(image_dir.glob("*.jpg"))

print("Number of images:", len(image_paths))

def get_breed(filename):
    name = Path(filename).stem

    # Remove the final _number
    breed = re.sub(r"_\d+$", "", name)

    return breed

for img in image_paths[-10:0:-1]:
    print(img.name, "->", get_breed(img.name))

breeds = sorted(set(get_breed(img.name) for img in image_paths))

print("Number of classes:", len(breeds))
print(breeds)

class_to_index = {
    breed: i
    for i, breed in enumerate(breeds)
}

labels = np.array([
    class_to_index[get_breed(img.name)]
    for img in image_paths
])

print("Labels shape:", labels.shape)
print("First 10 labels:", labels[:10])

# ============================================================
# INSPECT IMAGES AND LABELS
# ============================================================

import matplotlib.pyplot as plt
import numpy as np

# Select 12 random images
sample_indices = np.random.choice(
    len(image_paths),
    size=12,
    replace=False
)

plt.figure(figsize=(12, 10))

for i, idx in enumerate(sample_indices):

    # Load image
    image = plt.imread(image_paths[idx])

    plt.subplot(3, 4, i + 1)
    plt.imshow(image)

    # Display filename and corresponding breed
    plt.title(
        f"{image_paths[idx].name}\n{breeds[labels[idx]]}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

# ============================================================
# INSPECT DATASET AFTER LABELING
# ============================================================

import matplotlib.pyplot as plt
import numpy as np
from collections import Counter

# Basic dataset information
print("Number of images:", len(image_paths))
print("Number of classes:", len(breeds))
print("Image shape of first image:", image_paths[0])

# Show class distribution
class_counts = Counter(labels)

print("\nClass distribution:")
for i, breed in enumerate(breeds):
    print(f"{i}: {breed} -> {class_counts[i]} images")

# Plot class distribution
plt.figure(figsize=(14, 6))
plt.bar(range(len(breeds)), [class_counts[i] for i in range(len(breeds))])
plt.xlabel("Class Index")
plt.ylabel("Number of Images")
plt.title("Oxford-IIIT Pet Dataset Class Distribution")
plt.xticks(range(len(breeds)), breeds, rotation=90)
plt.tight_layout()
plt.show()

# Display sample images with their labels
plt.figure(figsize=(12, 8))

sample_indices = np.random.choice(
    len(image_paths),
    size=9,
    replace=False
)

for i, idx in enumerate(sample_indices):
    image = plt.imread(image_paths[idx])

    plt.subplot(3, 3, i + 1)
    plt.imshow(image)
    plt.title(
        f"Label: {labels[idx]}\n{breeds[labels[idx]]}"
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

# ============================================================
# BLOCK 3 — Train / Validation / Test Split
# ============================================================

from sklearn.model_selection import train_test_split

# First: 70% train, 30% temporary
train_paths, temp_paths, train_labels, temp_labels = train_test_split(
    image_paths,
    labels,
    test_size=0.30,
    random_state=42,
    stratify=labels
)

# Then: split temporary 50/50
val_paths, test_paths, val_labels, test_labels = train_test_split(
    temp_paths,
    temp_labels,
    test_size=0.50,
    random_state=42,
    stratify=temp_labels
)

print("Training:", len(train_paths))
print("Validation:", len(val_paths))
print("Test:", len(test_paths))

# ============================================================
# BLOCK 4 — Image Loading and MobileNetV2 Preprocessing
# ============================================================

import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

def load_image(image_path, label):
    # Read image
    image = tf.io.read_file(image_path)

    # Decode JPEG as RGB
    image = tf.image.decode_jpeg(image, channels=3)

    # Resize to MobileNetV2 input size
    image = tf.image.resize(image, IMG_SIZE)

    # Convert to float32
    image = tf.cast(image, tf.float32)

    # MobileNetV2 preprocessing
    image = preprocess_input(image)

    return image, label

# ============================================================
# BLOCK 5 — Create tf.data Datasets
# ============================================================

train_ds = tf.data.Dataset.from_tensor_slices(
    (np.array([str(x) for x in train_paths]), train_labels)
)

val_ds = tf.data.Dataset.from_tensor_slices(
    (np.array([str(x) for x in val_paths]), val_labels)
)

test_ds = tf.data.Dataset.from_tensor_slices(
    (np.array([str(x) for x in test_paths]), test_labels)
)

train_ds = train_ds.map(
    load_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

val_ds = val_ds.map(
    load_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

test_ds = test_ds.map(
    load_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

BATCH_SIZE = 32

train_ds = (
    train_ds
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

val_ds = (
    val_ds
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

test_ds = (
    test_ds
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

images, labels_batch = next(iter(train_ds))

print("Image batch shape:", images.shape)
print("Label batch shape:", labels_batch.shape)
print("Minimum pixel value:", tf.reduce_min(images).numpy())
print("Maximum pixel value:", tf.reduce_max(images).numpy())

# ============================================================
# BLOCK 6 — Display Sample Images
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

for images, labels_batch in train_ds.take(1):
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        # Images are MobileNetV2-preprocessed, so this is only
        # a structural check; the displayed values are not
        # original RGB pixel values.
        plt.imshow((images[i].numpy() + 1) / 2)
        plt.title(breeds[labels_batch[i].numpy()])
        plt.axis("off")

plt.tight_layout()
plt.show()

# ============================================================
# BLOCK 7 — Baseline MobileNetV2 Feature Extraction
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation="relu"),
    layers.Dense(37, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

# ============================================================
# BLOCK 8 — Helper Functions for the Remaining Experiments
# ============================================================

import time
import gc
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.applications import MobileNetV2

NUM_CLASSES = len(breeds)

def build_feature_extractor_model(
    initializer="glorot",
    regularization=None,
    dropout_rate=0.0,
    batch_normalization=False
):
    base = MobileNetV2(
        input_shape=(224, 224, 3),
        include_top=False,
        weights="imagenet"
    )
    base.trainable = False

    if initializer == "zero":
        kernel_init = tf.keras.initializers.Zeros()
    elif initializer == "random":
        kernel_init = tf.keras.initializers.RandomNormal(
            mean=0.0, stddev=0.05
        )
    elif initializer == "glorot":
        kernel_init = tf.keras.initializers.GlorotUniform()
    elif initializer == "he":
        kernel_init = tf.keras.initializers.HeNormal()
    else:
        raise ValueError("Unknown initializer")

    kernel_regularizer = None
    if regularization == "l2":
        kernel_regularizer = regularizers.l2(1e-4)

    model_layers = [
        base,
        layers.GlobalAveragePooling2D(),
    ]

    if batch_normalization:
        model_layers.append(layers.BatchNormalization())

    model_layers.append(
        layers.Dense(
            128,
            activation="relu",
            kernel_initializer=kernel_init,
            kernel_regularizer=kernel_regularizer
        )
    )

    if dropout_rate > 0:
        model_layers.append(layers.Dropout(dropout_rate))

    model_layers.append(
        layers.Dense(
            NUM_CLASSES,
            activation="softmax",
            kernel_initializer=kernel_init
        )
    )

    model = models.Sequential(model_layers)

    return model


def compile_model(model, optimizer="adam", learning_rate=1e-3):
    if optimizer == "sgd":
        opt = tf.keras.optimizers.SGD(learning_rate=learning_rate)
    elif optimizer == "momentum":
        opt = tf.keras.optimizers.SGD(
            learning_rate=learning_rate,
            momentum=0.9
        )
    elif optimizer == "rmsprop":
        opt = tf.keras.optimizers.RMSprop(
            learning_rate=learning_rate
        )
    elif optimizer == "adam":
        opt = tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        )
    else:
        raise ValueError("Unknown optimizer")

    model.compile(
        optimizer=opt,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model


def plot_history(history, title, metric="loss"):
    plt.figure(figsize=(8, 5))

    if metric == "loss":
        plt.plot(history.history["loss"], label="Training Loss")
        plt.plot(history.history["val_loss"], label="Validation Loss")
        plt.ylabel("Loss")
    else:
        plt.plot(history.history["accuracy"], label="Training Accuracy")
        plt.plot(
            history.history["val_accuracy"],
            label="Validation Accuracy"
        )
        plt.ylabel("Accuracy")

    plt.xlabel("Epoch")
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.show()


def make_dataset(paths, labels, batch_size=32, shuffle=False):
    ds = tf.data.Dataset.from_tensor_slices(
        (np.array([str(x) for x in paths]), np.array(labels))
    )
    ds = ds.map(
        load_image,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    if shuffle:
        ds = ds.shuffle(1000)

    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

    return ds

# ============================================================
# BLOCK 9 — Plot 1 & Plot 2: Weight Initialization
# ============================================================

STUDY_EPOCHS = 10

initializers = ["zero", "random", "glorot", "he"]
init_histories = {}

for init_name in initializers:
    print(f"\nTraining with {init_name} initialization...")

    tf.keras.backend.clear_session()

    init_model = build_feature_extractor_model(
        initializer=init_name
    )
    init_model = compile_model(
        init_model,
        optimizer="adam",
        learning_rate=1e-3
    )

    hist = init_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    init_histories[init_name] = hist.history

# Plot 1 — Training Loss
plt.figure(figsize=(8, 5))

for init_name in initializers:
    plt.plot(
        init_histories[init_name]["loss"],
        label=init_name
    )

plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Plot 1: Training Loss for Different Initializations")
plt.legend()
plt.grid(True)
plt.show()

# Plot 2 — Validation Accuracy
plt.figure(figsize=(8, 5))

for init_name in initializers:
    plt.plot(
        init_histories[init_name]["val_accuracy"],
        label=init_name
    )

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Plot 2: Validation Accuracy for Different Initializations")
plt.legend()
plt.grid(True)
plt.show()

best_initializer = max(
    initializers,
    key=lambda x: max(init_histories[x]["val_accuracy"])
)

print("Best initialization:", best_initializer)

# ============================================================
# BLOCK 10 — Plot 3 & Plot 4: Regularization
# ============================================================

regularization_settings = {
    "No Regularization": {
        "regularization": None,
        "dropout_rate": 0.0,
        "batch_normalization": False
    },
    "L2": {
        "regularization": "l2",
        "dropout_rate": 0.0,
        "batch_normalization": False
    },
    "Dropout": {
        "regularization": None,
        "dropout_rate": 0.5,
        "batch_normalization": False
    },
    "Batch Normalization": {
        "regularization": None,
        "dropout_rate": 0.0,
        "batch_normalization": True
    }
}

reg_histories = {}

for name, settings in regularization_settings.items():
    print(f"\nTraining: {name}")

    tf.keras.backend.clear_session()

    reg_model = build_feature_extractor_model(
        initializer=best_initializer,
        **settings
    )
    reg_model = compile_model(
        reg_model,
        optimizer="adam",
        learning_rate=1e-3
    )

    hist = reg_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    reg_histories[name] = hist.history

# Plot 3 — Training and Validation Accuracy
plt.figure(figsize=(10, 6))

for name, h in reg_histories.items():
    plt.plot(h["accuracy"], label=f"{name} - Train")
    plt.plot(h["val_accuracy"], "--", label=f"{name} - Val")

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Plot 3: Training and Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Plot 4 — Training and Validation Loss
plt.figure(figsize=(10, 6))

for name, h in reg_histories.items():
    plt.plot(h["loss"], label=f"{name} - Train")
    plt.plot(h["val_loss"], "--", label=f"{name} - Val")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Plot 4: Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# BLOCK 11 — Plot 5: With vs Without Batch Normalization
# ============================================================

bn_histories = {}

for use_bn in [False, True]:
    name = "With BN" if use_bn else "Without BN"

    tf.keras.backend.clear_session()

    bn_model = build_feature_extractor_model(
        initializer=best_initializer,
        batch_normalization=use_bn
    )
    bn_model = compile_model(
        bn_model,
        optimizer="adam",
        learning_rate=1e-3
    )

    hist = bn_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    bn_histories[name] = hist.history

plt.figure(figsize=(8, 5))

for name, h in bn_histories.items():
    plt.plot(h["val_accuracy"], label=name)

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Plot 5: With vs Without Batch Normalization")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# BLOCK 12 — Plot 6 & Plot 7: Optimization Algorithms
# ============================================================

optimizers = ["sgd", "momentum", "rmsprop", "adam"]
optimizer_histories = {}
optimizer_results = {}

for optimizer_name in optimizers:
    print(f"\nTraining with {optimizer_name}...")

    tf.keras.backend.clear_session()

    opt_model = build_feature_extractor_model(
        initializer=best_initializer
    )
    opt_model = compile_model(
        opt_model,
        optimizer=optimizer_name,
        learning_rate=1e-3
    )

    start_time = time.time()

    hist = opt_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    elapsed = time.time() - start_time

    optimizer_histories[optimizer_name] = hist.history

    optimizer_results[optimizer_name] = {
        "Final Loss": hist.history["loss"][-1],
        "Best Val Accuracy": max(hist.history["val_accuracy"]),
        "Time (s)": elapsed
    }

# Plot 6 — Training Loss
plt.figure(figsize=(8, 5))

for name, h in optimizer_histories.items():
    plt.plot(h["loss"], label=name)

plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Plot 6: Training Loss for Different Optimizers")
plt.legend()
plt.grid(True)
plt.show()

# Plot 7 — Validation Accuracy
plt.figure(figsize=(8, 5))

for name, h in optimizer_histories.items():
    plt.plot(h["val_accuracy"], label=name)

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Plot 7: Validation Accuracy for Different Optimizers")
plt.legend()
plt.grid(True)
plt.show()

optimizer_table = pd.DataFrame(optimizer_results).T
display(optimizer_table)

best_optimizer = optimizer_table["Best Val Accuracy"].idxmax()
print("Best optimizer:", best_optimizer)

# ============================================================
# BLOCK 13 — Plot 8: Learning Rate Tuning
# ============================================================

learning_rates = [0.001, 0.0001]
lr_results = {}

for lr in learning_rates:
    print(f"\nLearning rate = {lr}")

    tf.keras.backend.clear_session()

    lr_model = build_feature_extractor_model(
        initializer=best_initializer,
        dropout_rate=0.25
    )
    lr_model = compile_model(
        lr_model,
        optimizer=best_optimizer,
        learning_rate=lr
    )

    hist = lr_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    lr_results[lr] = max(hist.history["val_accuracy"])

plt.figure(figsize=(7, 5))
plt.plot(
    list(lr_results.keys()),
    list(lr_results.values()),
    marker="o"
)
plt.xscale("log")
plt.xlabel("Learning Rate")
plt.ylabel("Validation Accuracy")
plt.title("Plot 8: Learning Rate vs Validation Accuracy")
plt.grid(True)
plt.show()

best_lr = max(lr_results, key=lr_results.get)
print("Best learning rate:", best_lr)

# ============================================================
# BLOCK 14 — Plot 9: Batch Size Tuning
# ============================================================

batch_sizes = [16, 32, 64]
batch_results = {}

for bs in batch_sizes:
    print(f"\nBatch size = {bs}")

    train_bs = make_dataset(
        train_paths,
        train_labels,
        batch_size=bs,
        shuffle=True
    )
    val_bs = make_dataset(
        val_paths,
        val_labels,
        batch_size=bs
    )

    tf.keras.backend.clear_session()

    bs_model = build_feature_extractor_model(
        initializer=best_initializer,
        dropout_rate=0.25
    )
    bs_model = compile_model(
        bs_model,
        optimizer=best_optimizer,
        learning_rate=best_lr
    )

    hist = bs_model.fit(
        train_bs,
        validation_data=val_bs,
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    batch_results[bs] = max(hist.history["val_accuracy"])

plt.figure(figsize=(7, 5))
plt.plot(
    list(batch_results.keys()),
    list(batch_results.values()),
    marker="o"
)
plt.xlabel("Batch Size")
plt.ylabel("Validation Accuracy")
plt.title("Plot 9: Batch Size vs Validation Accuracy")
plt.grid(True)
plt.show()

best_batch_size = max(batch_results, key=batch_results.get)
print("Best batch size:", best_batch_size)

# ============================================================
# BLOCK 15 — Plot 10: Dropout Tuning
# ============================================================

dropout_rates = [0.0, 0.25, 0.5]
dropout_results = {}

for dropout in dropout_rates:
    print(f"\nDropout = {dropout}")

    tf.keras.backend.clear_session()

    dropout_model = build_feature_extractor_model(
        initializer=best_initializer,
        dropout_rate=dropout
    )
    dropout_model = compile_model(
        dropout_model,
        optimizer=best_optimizer,
        learning_rate=best_lr
    )

    hist = dropout_model.fit(
        make_dataset(
            train_paths,
            train_labels,
            batch_size=best_batch_size,
            shuffle=True
        ),
        validation_data=make_dataset(
            val_paths,
            val_labels,
            batch_size=best_batch_size
        ),
        epochs=STUDY_EPOCHS,
        verbose=1
    )

    dropout_results[dropout] = max(hist.history["val_accuracy"])

plt.figure(figsize=(7, 5))
plt.plot(
    list(dropout_results.keys()),
    list(dropout_results.values()),
    marker="o"
)
plt.xlabel("Dropout Rate")
plt.ylabel("Validation Accuracy")
plt.title("Plot 10: Dropout Rate vs Validation Accuracy")
plt.grid(True)
plt.show()

best_dropout = max(dropout_results, key=dropout_results.get)
print("Best dropout:", best_dropout)

# ============================================================
# BLOCK 16 — Plot 11 & Plot 12: Feature Extraction vs Fine-Tuning
# ============================================================

# Feature extraction
tf.keras.backend.clear_session()

feature_model = build_feature_extractor_model(
    initializer=best_initializer,
    dropout_rate=best_dropout
)
feature_model = compile_model(
    feature_model,
    optimizer=best_optimizer,
    learning_rate=best_lr
)

feature_history = feature_model.fit(
    make_dataset(
        train_paths,
        train_labels,
        batch_size=best_batch_size,
        shuffle=True
    ),
    validation_data=make_dataset(
        val_paths,
        val_labels,
        batch_size=best_batch_size
    ),
    epochs=STUDY_EPOCHS,
    verbose=1
)

# Fine-tuning
tf.keras.backend.clear_session()

fine_tune_model = build_feature_extractor_model(
    initializer=best_initializer,
    dropout_rate=best_dropout
)

base = fine_tune_model.layers[0]

# First freeze everything.
base.trainable = True

# Freeze most layers and unfreeze only the upper layers.
fine_tune_at = len(base.layers) - 20

for layer in base.layers[:fine_tune_at]:
    layer.trainable = False

# Keep BatchNorm layers frozen during fine-tuning.
for layer in base.layers[fine_tune_at:]:
    if isinstance(layer, layers.BatchNormalization):
        layer.trainable = False

fine_tune_model = compile_model(
    fine_tune_model,
    optimizer=best_optimizer,
    learning_rate=1e-5
)

fine_history = fine_tune_model.fit(
    make_dataset(
        train_paths,
        train_labels,
        batch_size=best_batch_size,
        shuffle=True
    ),
    validation_data=make_dataset(
        val_paths,
        val_labels,
        batch_size=best_batch_size
    ),
    epochs=STUDY_EPOCHS,
    verbose=1
)

# Plot 11 — Validation Accuracy
plt.figure(figsize=(8, 5))

plt.plot(
    feature_history.history["val_accuracy"],
    label="Feature Extraction"
)
plt.plot(
    fine_history.history["val_accuracy"],
    label="Fine-Tuning"
)

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Plot 11: Feature Extraction vs Fine-Tuning")
plt.legend()
plt.grid(True)
plt.show()

# Plot 12 — Training and Validation Loss
plt.figure(figsize=(9, 6))

plt.plot(
    feature_history.history["loss"],
    label="Feature Extraction - Train"
)
plt.plot(
    feature_history.history["val_loss"],
    "--",
    label="Feature Extraction - Val"
)
plt.plot(
    fine_history.history["loss"],
    label="Fine-Tuning - Train"
)
plt.plot(
    fine_history.history["val_loss"],
    "--",
    label="Fine-Tuning - Val"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Plot 12: Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# BLOCK 17 — Prepare Configurations for 5-Fold Cross-Validation
# ============================================================

from sklearn.model_selection import StratifiedKFold

# Combine only TRAIN + VALIDATION.
# The independent TEST set is deliberately excluded.
cv_paths = np.concatenate([
    np.array(train_paths),
    np.array(val_paths)
])

cv_labels = np.concatenate([
    np.array(train_labels),
    np.array(val_labels)
])

configs = [
    {
        "name": "C1",
        "learning_rate": best_lr,
        "batch_size": best_batch_size,
        "dropout": best_dropout,
        "optimizer": best_optimizer,
        "fine_tune": False
    },
    {
        "name": "C2",
        "learning_rate": best_lr,
        "batch_size": best_batch_size,
        "dropout": 0.25,
        "optimizer": "adam",
        "fine_tune": False
    },
    {
        "name": "C3",
        "learning_rate": 1e-4,
        "batch_size": 32,
        "dropout": 0.5,
        "optimizer": "adam",
        "fine_tune": False
    },
    {
        "name": "C4",
        "learning_rate": 1e-5,
        "batch_size": best_batch_size,
        "dropout": best_dropout,
        "optimizer": "adam",
        "fine_tune": True
    }
]

configs

# ============================================================
# BLOCK 18 — 5-Fold Cross-Validation
# ============================================================

# For a full lab run, you can increase this to 5 or 10.
CV_EPOCHS = 3

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_scores = {}

for config in configs:
    print("\n" + "=" * 60)
    print("Configuration:", config["name"])
    print("=" * 60)

    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(cv_paths, cv_labels),
        start=1
    ):
        print(f"\nFold {fold}/5")

        fold_train_paths = cv_paths[train_idx]
        fold_train_labels = cv_labels[train_idx]

        fold_val_paths = cv_paths[val_idx]
        fold_val_labels = cv_labels[val_idx]

        fold_train_ds = make_dataset(
            fold_train_paths,
            fold_train_labels,
            batch_size=config["batch_size"],
            shuffle=True
        )

        fold_val_ds = make_dataset(
            fold_val_paths,
            fold_val_labels,
            batch_size=config["batch_size"]
        )

        tf.keras.backend.clear_session()
        gc.collect()

        fold_model = build_feature_extractor_model(
            initializer=best_initializer,
            dropout_rate=config["dropout"]
        )

        if config["fine_tune"]:
            base = fold_model.layers[0]
            base.trainable = True

            fine_tune_at = len(base.layers) - 20

            for layer in base.layers[:fine_tune_at]:
                layer.trainable = False

            for layer in base.layers[fine_tune_at:]:
                if isinstance(layer, layers.BatchNormalization):
                    layer.trainable = False

        fold_model = compile_model(
            fold_model,
            optimizer=config["optimizer"],
            learning_rate=config["learning_rate"]
        )

        fold_model.fit(
            fold_train_ds,
            validation_data=fold_val_ds,
            epochs=CV_EPOCHS,
            verbose=0
        )

        _, fold_accuracy = fold_model.evaluate(
            fold_val_ds,
            verbose=0
        )

        fold_scores.append(fold_accuracy)

        print(f"Fold {fold} accuracy: {fold_accuracy:.4f}")

        del fold_model
        gc.collect()

    cv_scores[config["name"]] = fold_scores

cv_table = pd.DataFrame(
    cv_scores,
    index=[f"F{i}" for i in range(1, 6)]
)

cv_table.loc["Mean"] = cv_table.mean()
cv_table.loc["SD"] = cv_table.iloc[:5].std(ddof=0)

display(cv_table)

cv_mean = cv_table.loc["Mean"]
cv_sd = cv_table.loc["SD"]

best_cv_config_name = cv_mean.idxmax()

print("Best CV configuration:", best_cv_config_name)
print("Mean CV accuracy:", cv_mean[best_cv_config_name])
print("CV SD:", cv_sd[best_cv_config_name])

# ============================================================
# BLOCK 19 — Plot 13: 5-Fold Cross-Validation Accuracy
# ============================================================

plt.figure(figsize=(9, 6))

means = [
    cv_mean[name]
    for name in cv_mean.index
]

errors = [
    cv_sd[name]
    for name in cv_mean.index
]

plt.bar(
    cv_mean.index,
    means,
    yerr=errors,
    capsize=5
)

plt.xlabel("Hyperparameter Configuration")
plt.ylabel("Mean Validation Accuracy")
plt.title("Plot 13: 5-Fold Cross-Validation Accuracy")
plt.grid(axis="y")

plt.show()

# ============================================================
# BLOCK 20 — Retrain Best Configuration on Complete Training Data
# ============================================================

best_config = next(
    config for config in configs
    if config["name"] == best_cv_config_name
)

print("Selected configuration:")
print(best_config)

# Complete training data = original train + validation.
final_train_paths = cv_paths
final_train_labels = cv_labels

final_train_ds = make_dataset(
    final_train_paths,
    final_train_labels,
    batch_size=best_config["batch_size"],
    shuffle=True
)

# The test set is used ONLY now.
final_test_ds = make_dataset(
    test_paths,
    test_labels,
    batch_size=best_config["batch_size"]
)

tf.keras.backend.clear_session()

final_model = build_feature_extractor_model(
    initializer=best_initializer,
    dropout_rate=best_config["dropout"]
)

if best_config["fine_tune"]:
    base = final_model.layers[0]
    base.trainable = True

    fine_tune_at = len(base.layers) - 20

    for layer in base.layers[:fine_tune_at]:
        layer.trainable = False

    for layer in base.layers[fine_tune_at:]:
        if isinstance(layer, layers.BatchNormalization):
            layer.trainable = False

final_model = compile_model(
    final_model,
    optimizer=best_config["optimizer"],
    learning_rate=best_config["learning_rate"]
)

start_time = time.time()

final_history = final_model.fit(
    final_train_ds,
    epochs=10,
    verbose=1
)

training_time = time.time() - start_time

final_model.summary()

# ============================================================
# BLOCK 21 — Final Test Evaluation
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

test_probabilities = final_model.predict(
    final_test_ds,
    verbose=1
)

test_predictions = np.argmax(
    test_probabilities,
    axis=1
)

true_labels = np.concatenate([
    labels_batch.numpy()
    for _, labels_batch in final_test_ds
])

test_accuracy = accuracy_score(
    true_labels,
    test_predictions
)

precision = precision_score(
    true_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    true_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    true_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)

num_parameters = final_model.count_params()

final_metrics = pd.DataFrame({
    "Metric": [
        "Mean CV Accuracy",
        "CV Standard Deviation",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1-score",
        "Training Time (seconds)",
        "Number of Parameters"
    ],
    "Value": [
        cv_mean[best_cv_config_name],
        cv_sd[best_cv_config_name],
        test_accuracy,
        precision,
        recall,
        f1,
        training_time,
        num_parameters
    ]
})

display(final_metrics)

# ============================================================
# BLOCK 22 — Plot 14: Confusion Matrix
# ============================================================

import seaborn as sns

cm = confusion_matrix(
    true_labels,
    test_predictions
)

plt.figure(figsize=(16, 14))

sns.heatmap(
    cm,
    annot=False,
    cmap="Blues",
    xticklabels=breeds,
    yticklabels=breeds
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("Plot 14: Confusion Matrix")

plt.xticks(rotation=90)
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# ============================================================
# BLOCK 23 — Plot 15: Representative Misclassified Images
# ============================================================

# Reload a small number of original test images so they can be
# displayed as normal RGB images.

num_examples = 9

plt.figure(figsize=(12, 12))

shown = 0

for path_value, true_label, predicted_label in zip(
    test_paths,
    test_labels,
    test_predictions
):
    if true_label != predicted_label:
        image = tf.io.read_file(str(path_value))
        image = tf.image.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, IMG_SIZE)

        plt.subplot(3, 3, shown + 1)
        plt.imshow(tf.cast(image, tf.uint8))
        plt.title(
            f"True: {breeds[true_label]}\n"
            f"Pred: {breeds[predicted_label]}"
        )
        plt.axis("off")

        shown += 1

        if shown == num_examples:
            break

if shown > 0:
    plt.tight_layout()
    plt.show()
else:
    print("No misclassified examples found.")

# ============================================================
# BLOCK 24 — Overall Results Table
# ============================================================

overall_results = pd.DataFrame({
    "Configuration": [
        "Baseline",
        f"Best Initialization ({best_initializer})",
        "Best Regularization",
        f"Best Optimizer ({best_optimizer})",
        "Best Hyperparameters",
        "Fine-Tuned Model"
    ],
    "CV Accuracy": [
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        cv_mean[best_cv_config_name],
        cv_mean[best_cv_config_name] if best_config["fine_tune"] else np.nan
    ],
    "SD": [
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        cv_sd[best_cv_config_name],
        cv_sd[best_cv_config_name] if best_config["fine_tune"] else np.nan
    ],
    "Test Accuracy": [
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        test_accuracy,
        test_accuracy if best_config["fine_tune"] else np.nan
    ],
    "Training Time (s)": [
        np.nan,
        np.nan,
        np.nan,
        np.nan,
        training_time,
        training_time if best_config["fine_tune"] else np.nan
    ]
})

display(overall_results)

print("\nFINAL MODEL JUSTIFICATION")
print("-------------------------")
print(
    f"Selected configuration: {best_cv_config_name}. "
    f"It achieved mean CV accuracy of "
    f"{cv_mean[best_cv_config_name]:.4f} "
    f"with SD {cv_sd[best_cv_config_name]:.4f}."
)
print(
    f"Independent test accuracy: {test_accuracy:.4f}, "
    f"with F1-score: {f1:.4f}."
)
print(
    "The final choice should consider accuracy, variability, "
    "training cost and generalization rather than validation "
    "accuracy alone."
)

# ============================================================
# BLOCK 25 — Required Discussion Questions
# ============================================================

discussion_answers = {
    1: "Parameters are learned from data, while hyperparameters are chosen before/during training, such as learning rate, batch size and dropout rate.",
    2: "Weight initialization determines the starting point of training. A suitable initialization helps gradients and activations remain in useful ranges and can improve convergence.",
    3: "Zero initialization gives neurons identical gradients, so neurons in the same layer remain symmetric and learn the same features.",
    4: "Xavier/Glorot initialization is generally suited to keeping activation variance stable for activations such as tanh, while He initialization is designed particularly for ReLU-like activations and uses a larger variance.",
    5: "Overfitting can be identified when training accuracy continues increasing while validation accuracy stops improving or decreases, often accompanied by increasing validation loss.",
    6: "Dropout randomly disables a fraction of activations during training, preventing excessive dependence on particular neurons and encouraging more robust representations.",
    7: "Batch Normalization normalizes activations within mini-batches and then applies learnable scale and shift parameters.",
    8: "For [2,4,6,8], the mean is 5 and the variance is 5. Normalizing gives approximately [-1.342,-0.447,0.447,1.342] when epsilon is ignored.",
    9: "Gamma controls the learned scale and beta controls the learned shift after normalization.",
    10: "SGD updates parameters using the current gradient; Momentum accumulates a velocity from past gradients; RMSProp adapts the learning rate using recent squared gradients; Adam combines momentum-like first-moment tracking with adaptive second-moment scaling.",
    11: "A learning rate that is too large can cause unstable training, overshooting, or divergence.",
    12: "A learning rate that is too small can make training extremely slow and may leave the model stuck before reaching a good solution.",
    13: "Increasing batch size generally gives more stable gradient estimates and can improve computational efficiency, but it may require more memory and can sometimes affect generalization.",
    14: "Stride is the step size of a convolution filter. Padding adds pixels around the input so spatial dimensions can be preserved or controlled.",
    15: "MobileNetV2 is computationally efficient because it uses depthwise separable convolutions, inverted residual blocks and linear bottlenecks.",
    16: "Depthwise separable convolution separates spatial filtering from channel mixing, substantially reducing computation compared with a standard convolution.",
    17: "Transfer learning reuses knowledge learned by a pretrained model for a new task.",
    18: "Feature extraction freezes the pretrained base and trains a new classifier. Fine-tuning unfreezes selected pretrained layers and adapts them to the new dataset.",
    19: "A smaller learning rate protects useful pretrained features from being changed too aggressively.",
    20: "K-Fold cross-validation evaluates configurations across multiple train/validation splits, giving a more reliable estimate of performance and variability.",
    21: "Using the test set during tuning leaks information from the final evaluation set and produces an overly optimistic estimate of generalization.",
    22: "The mean measures typical performance while the standard deviation measures how much performance varies between folds.",
    23: "No. A model should also be considered in terms of variability, computational cost, overfitting and final independent test performance."
}

for q, answer in discussion_answers.items():
    print(f"{q}. {answer}\n")
