# -*- coding: utf-8 -*-
"""Lab-4-Dl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tf7XcEZa3a3AQd5CKGM0jmzZB7TPLM11
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16, ResNet50, MobileNetV2
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.utils import to_categorical

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Load CIFAR-10 dataset
data = np.load("cifar10.npz")

x_train = data["x_train"]
y_train = data["y_train"]
x_test = data["x_test"]
y_test = data["y_test"]
# Normalize pixel values to the range [0, 1]
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# CIFAR-10 class names
class_names = [
    "Airplane", "Automobile", "Bird", "Cat", "Deer",
    "Dog", "Frog", "Horse", "Ship", "Truck"
]

# Print dataset dimensions
print("Training images shape :", x_train.shape)
print("Training labels shape :", y_train.shape)
print("Testing images shape  :", x_test.shape)
print("Testing labels shape  :", y_test.shape)

# Display 10 sample images
plt.figure(figsize=(15, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis("off")

plt.tight_layout()
plt.show()

# Verify normalization
print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

# Convert labels to one-hot encoding
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

print("Training labels shape:", y_train_cat.shape)
print("Testing labels shape :", y_test_cat.shape)

# Load VGG16 pretrained on ImageNet
base_model = VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(32, 32, 3)
)

# Freeze the convolutional base
base_model.trainable = False

# Display model information
base_model.summary()

# Build the transfer learning model

model = models.Sequential([
    base_model,

    # Convert feature maps into a single feature vector
    layers.GlobalAveragePooling2D(),

    # New classifier
    layers.Dense(128, activation="relu"),

    # CIFAR-10 has 10 classes
    layers.Dense(10, activation="softmax")
])

# Display the complete model
model.summary()

# Compile the transfer learning model

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("Model compiled successfully.")

# Train the transfer learning model

start_time = time.time()

history = model.fit(
    x_train,
    y_train_cat,
    validation_data=(x_test, y_test_cat),
    epochs=10,
    batch_size=32,
    verbose=1
)

training_time = time.time() - start_time

print(f"\nTraining time: {training_time:.2f} seconds")

# Plot Accuracy
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.savefig('accuracy_loss_plots.png', dpi=150)
plt.show()

# Evaluate base transfer learning model
test_loss, test_accuracy = model.evaluate(x_test, y_test_cat, verbose=1)
print(f"\nTest Loss (before fine-tuning): {test_loss:.4f}")
print(f"Test Accuracy (before fine-tuning): {test_accuracy:.4f}")

# Unfreeze the last block of the base model for fine-tuning
base_model.trainable = True

# Freeze all layers except the last block
fine_tune_at = len(base_model.layers) - 4  # unfreezes last ~4 layers (adjust as needed)

for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

# Recompile with a lower learning rate (important for fine-tuning)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

print(len(base_model.layers))

start_time = time.time()

fine_tune_epochs = 10
total_epochs = 10 + fine_tune_epochs

history_fine = model.fit(
    x_train,
    y_train_cat,
    validation_data=(x_test, y_test_cat),
    epochs=total_epochs,
    initial_epoch=history.epoch[-1] + 1,
    batch_size=32,
    verbose=1
)

fine_tune_time = time.time() - start_time
print(f"\nFine-tuning time: {fine_tune_time:.2f} seconds")

test_loss_ft, test_accuracy_ft = model.evaluate(x_test, y_test_cat, verbose=1)

print(f"Accuracy before fine-tuning: {test_accuracy:.4f}")
print(f"Accuracy after fine-tuning:  {test_accuracy_ft:.4f}")
print(f"Improvement: {(test_accuracy_ft - test_accuracy)*100:.2f}%")

# Combine history for full plot
acc = history.history['accuracy'] + history_fine.history['accuracy']
val_acc = history.history['val_accuracy'] + history_fine.history['val_accuracy']
loss = history.history['loss'] + history_fine.history['loss']
val_loss = history.history['val_loss'] + history_fine.history['val_loss']

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.axvline(x=10, color='gray', linestyle='--', label='Fine-tuning starts')
plt.title('Accuracy (Full Training + Fine-Tuning)')
plt.xlabel('Epoch')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.axvline(x=10, color='gray', linestyle='--', label='Fine-tuning starts')
plt.title('Loss (Full Training + Fine-Tuning)')
plt.xlabel('Epoch')
plt.legend()

plt.tight_layout()
plt.savefig('full_training_plots.png', dpi=150)
plt.show()

from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score
import seaborn as sns
import numpy as np

# Get predictions
y_pred_probs = model.predict(x_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test_cat, axis=1)

class_names = ['Airplane', 'Automobile', 'Bird', 'Cat', 'Deer',
                'Dog', 'Frog', 'Horse', 'Ship', 'Truck']

# Precision, Recall, F1 (macro-averaged, standard for multi-class)
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')

print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

# Find misclassified indices
misclassified_idx = np.where(y_pred != y_true)[0]
print(f"Total misclassified: {len(misclassified_idx)} out of {len(y_true)}")

# Plot a sample of 10 misclassified images
plt.figure(figsize=(15, 6))
sample_idx = np.random.choice(misclassified_idx, 10, replace=False)

for i, idx in enumerate(sample_idx):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_test[idx])
    plt.title(f"True: {class_names[y_true[idx]]}\nPred: {class_names[y_pred[idx]]}", fontsize=9)
    plt.axis('off')

plt.tight_layout()
plt.savefig('misclassified_images.png', dpi=150)
plt.show()

print(6)

print(10)

print(13)

results = {}  # will store {model_name: {params, accuracy, time}}

def build_lenet5():
    model = models.Sequential([
        layers.Conv2D(6, (5,5), activation='relu', padding='same', input_shape=(32,32,3)),
        layers.AveragePooling2D((2,2)),
        layers.Conv2D(16, (5,5), activation='relu'),
        layers.AveragePooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(120, activation='relu'),
        layers.Dense(84, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])
    return model

lenet = build_lenet5()
lenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

start = time.time()
history_lenet = lenet.fit(x_train, y_train_cat, epochs=10, batch_size=64,
                           validation_split=0.1, verbose=1)
train_time_lenet = time.time() - start

test_loss, test_acc = lenet.evaluate(x_test, y_test_cat, verbose=0)
results['LeNet-5'] = {
    'params': lenet.count_params(),
    'accuracy': test_acc * 100,
    'time': train_time_lenet
}
print(f"LeNet-5 -> Params: {lenet.count_params():,} | Accuracy: {test_acc*100:.2f}% | Time: {train_time_lenet:.2f}s")

print(5)

print(7)

print(8)

print(200)

print(1000)

print(10)

def build_alexnet():
    model = models.Sequential([
        layers.Conv2D(96, (3,3), strides=1, activation='relu', padding='same', input_shape=(32,32,3)),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(256, (3,3), activation='relu', padding='same'),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(384, (3,3), activation='relu', padding='same'),
        layers.Conv2D(384, (3,3), activation='relu', padding='same'),
        layers.Conv2D(256, (3,3), activation='relu', padding='same'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(1024, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(1024, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(10, activation='softmax')
    ])
    return model

alexnet = build_alexnet()
alexnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

start = time.time()
history_alexnet = alexnet.fit(x_train, y_train_cat, epochs=10, batch_size=64,
                               validation_split=0.1, verbose=1)
train_time_alexnet = time.time() - start

test_loss, test_acc = alexnet.evaluate(x_test, y_test_cat, verbose=0)
results['AlexNet'] = {
    'params': alexnet.count_params(),
    'accuracy': test_acc * 100,
    'time': train_time_alexnet
}
print(f"AlexNet -> Params: {alexnet.count_params():,} | Accuracy: {test_acc*100:.2f}% | Time: {train_time_alexnet:.2f}s")

def inception_module(x, f1, f3_reduce, f3, f5_reduce, f5, pool_proj):
    conv1 = layers.Conv2D(f1, (1,1), padding='same', activation='relu')(x)

    conv3 = layers.Conv2D(f3_reduce, (1,1), padding='same', activation='relu')(x)
    conv3 = layers.Conv2D(f3, (3,3), padding='same', activation='relu')(conv3)

    conv5 = layers.Conv2D(f5_reduce, (1,1), padding='same', activation='relu')(x)
    conv5 = layers.Conv2D(f5, (5,5), padding='same', activation='relu')(conv5)

    pool = layers.MaxPooling2D((3,3), strides=(1,1), padding='same')(x)
    pool = layers.Conv2D(pool_proj, (1,1), padding='same', activation='relu')(pool)

    return layers.concatenate([conv1, conv3, conv5, pool], axis=-1)

def build_googlenet():
    inputs = layers.Input(shape=(32,32,3))
    x = layers.Conv2D(64, (3,3), padding='same', activation='relu')(inputs)
    x = layers.MaxPooling2D((2,2))(x)

    x = inception_module(x, 64, 96, 128, 16, 32, 32)
    x = inception_module(x, 128, 128, 192, 32, 96, 64)
    x = layers.MaxPooling2D((2,2))(x)

    x = inception_module(x, 192, 96, 208, 16, 48, 64)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(10, activation='softmax')(x)

    return models.Model(inputs, outputs)

googlenet = build_googlenet()
googlenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

start = time.time()
history_googlenet = googlenet.fit(x_train, y_train_cat, epochs=10, batch_size=64,
                                   validation_split=0.1, verbose=1)
train_time_googlenet = time.time() - start

test_loss, test_acc = googlenet.evaluate(x_test, y_test_cat, verbose=0)
results['GoogleNet'] = {
    'params': googlenet.count_params(),
    'accuracy': test_acc * 100,
    'time': train_time_googlenet
}
print(f"GoogleNet -> Params: {googlenet.count_params():,} | Accuracy: {test_acc*100:.2f}% | Time: {train_time_googlenet:.2f}s")

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

# Preprocess for ResNet50 (expects specific normalization, not just /255)
x_train_resnet = preprocess_input(x_train * 255.0)
x_test_resnet = preprocess_input(x_test * 255.0)

base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(32,32,3))
base_model.trainable = True  # <-- fully trainable, no freezing

resnet_model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

resnet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),  # slightly lower LR since full network is training
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

start = time.time()
history_resnet = resnet_model.fit(
    x_train_resnet, y_train_cat,
    epochs=10, batch_size=64,
    validation_split=0.1, verbose=1
)
train_time_resnet = time.time() - start

test_loss, test_acc = resnet_model.evaluate(x_test_resnet, y_test_cat, verbose=0)

results['ResNet50'] = {
    'params': resnet_model.count_params(),
    'accuracy': test_acc * 100,
    'time': train_time_resnet
}
print(f"ResNet50 -> Params: {resnet_model.count_params():,} | Accuracy: {test_acc*100:.2f}% | Time: {train_time_resnet:.2f}s")

from tensorflow.keras.applications import VGG16
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras import layers, models
import time

def build_model(dense_units=128, frozen='All'):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(32,32,3))
    if frozen == 'All':
        base_model.trainable = False
    else:  # Partial -> unfreeze last conv block
        base_model.trainable = True
        fine_tune_at = len(base_model.layers) - 4
        for layer in base_model.layers[:fine_tune_at]:
            layer.trainable = False

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(dense_units, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])
    return model

def run_experiment(name, lr=0.001, batch_size=32, epochs=10,
                    optimizer_name='Adam', dense_units=128, frozen='All'):
    model = build_model(dense_units=dense_units, frozen=frozen)
    optimizer = Adam(learning_rate=lr) if optimizer_name == 'Adam' else SGD(learning_rate=lr)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

    start = time.time()
    history = model.fit(x_train, y_train_cat, epochs=epochs, batch_size=batch_size,
                         validation_split=0.1, verbose=0)
    elapsed = time.time() - start

    test_loss, test_acc = model.evaluate(x_test, y_test_cat, verbose=0)
    print(f"{name:<18} | LR={lr:<7} Batch={batch_size:<3} Epochs={epochs:<3} "
          f"Opt={optimizer_name:<4} Dense={dense_units:<4} Frozen={frozen:<8} "
          f"-> Acc={test_acc*100:.2f}%  Time={elapsed:.2f}s")

    return {'name': name, 'lr': lr, 'batch_size': batch_size, 'epochs': epochs,
            'optimizer': optimizer_name, 'dense_units': dense_units, 'frozen': frozen,
            'accuracy': test_acc * 100, 'time': elapsed}

results_hp = []

# Baseline configuration
results_hp.append(run_experiment('Baseline',
    lr=0.001, batch_size=32, epochs=10, optimizer_name='Adam', dense_units=128, frozen='All'))

# Vary Learning Rate
results_hp.append(run_experiment('LR=0.0001',
    lr=0.0001, batch_size=32, epochs=10, optimizer_name='Adam', dense_units=128, frozen='All'))

# Vary Batch Size
results_hp.append(run_experiment('Batch=16',
    lr=0.001, batch_size=16, epochs=10, optimizer_name='Adam', dense_units=128, frozen='All'))
results_hp.append(run_experiment('Batch=64',
    lr=0.001, batch_size=64, epochs=10, optimizer_name='Adam', dense_units=128, frozen='All'))

# Vary Epochs
results_hp.append(run_experiment('Epochs=20',
    lr=0.001, batch_size=32, epochs=20, optimizer_name='Adam', dense_units=128, frozen='All'))

# Vary Optimizer
results_hp.append(run_experiment('Optimizer=SGD',
    lr=0.001, batch_size=32, epochs=10, optimizer_name='SGD', dense_units=128, frozen='All'))

# Vary Dense Units
results_hp.append(run_experiment('Dense=256',
    lr=0.001, batch_size=32, epochs=10, optimizer_name='Adam', dense_units=256, frozen='All'))

# Vary Frozen Layers
results_hp.append(run_experiment('Frozen=Partial',
    lr=0.001, batch_size=32, epochs=10, optimizer_name='Adam', dense_units=128, frozen='Partial'))

